Excluded:
  - lib/**/*

Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - src/humanize_time.cr
  Enabled: true
  Severity: Convention
